### ISSUE TITLE
crashes on startup

### ISSUE THREAD

**Issue by damianatorrpm** [flathub/org.fdroid.Repomaker#10]
Installation succeeds
```
[tux@localhost ~]$ flatpak install repomaker
 1. [✓] org.fdroid.Repomaker.Locale           stable           i           flathub            3.1 kB / 2.1 MB
 2. [✓] org.fdroid.Repomaker                  stable           i           flathub          116.1 MB / 137.6 MB
```

But crashes on startup:
```
[tux@localhost ~]$ flatpak run org.fdroid.Repomaker
Traceback (most recent call last):
  File "/app/bin/repomaker", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3250, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pygments>=2.3.1' distribution was not found and is required by androguard
```

**Comment by roke-julian-lockhart** [comment]
[This is occurring for me also.](http://github.com/flathub/org.fdroid.Repomaker/files/7220984/default.DAT.BIN.TXT.LOG)
